---
name: Bygg & distribuera Node.js till Azure (blueroute)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # krävs för actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Ställ in Node.js-version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm ci, build och test
        working-directory: ./Web
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      # ⬇️ Ladda upp den färdigbyggda mappen (ändra till ./Web/dist om Vite)
      - name: Ladda upp artefakt för deployment
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./Web/build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # krävs för OIDC-inloggning
      contents: read # krävs för actions/checkout

    steps:
      - name: Ladda ner artefakt
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./site

      - name: Logga in i Azure
        uses: azure/login@v2
        with:
          client-id: >-
            ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B48A3F7C4A740CE956BAD9B36DF28D3 }}
          tenant-id: >-
            ${{ secrets.AZUREAPPSERVICE_TENANTID_090304F2AC4B43C4B271B140F7B4E63B }}
          subscription-id: >-
            ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9EC3A0CB627F497BB20D524961ECDF3A }}

      - name: Distribuera till Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "blueroute"
          slot-name: "Production"
          package: ./site
